#!/bin/sh

# Compile porous models libraries 
wclean libs/petroleumTransportModels
wclean libs/relativePermeabilityModels
wclean libs/capillaryPressureModels
wclean libs/wellModels

find . -type d -iname "lnInclude" -exec rm -r {} +
find . -type d -iname "linux*" -exec rm -r {} +
# Compile solvers 
#wclean all solvers
