# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'OpenRSR'
copyright = '2020, Fadeli Mohammed Elwardi'
author = 'Fadeli Mohammed Elwardi'

# The full version, including alpha/beta/rc tags
release = '0.0.1'

import os
repo_root = os.environ.get('OPENRSR_ROOT')

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    #'sphinx.ext.mathjax',
    'breathe',
    'exhale',
    'sphinx.ext.graphviz',
    'sphinx.ext.inheritance_diagram'
]

# Setup the breathe extension
breathe_projects = {
    "OpenRSR": repo_root+"/docs/Doxygen/xml"
}
breathe_default_project = "OpenRSR"

# Setup the exhale extension
exhale_args = {
        # These arguments are required
        "containmentFolder":     "./api",
        "rootFileName":          "library_root.rst",
        "rootFileTitle":         "Library API",
        "doxygenStripFromPath":  repo_root,
        # Suggested optional arguments
        "createTreeView":        True,
        # TIP: if using the sphinx-bootstrap-theme, you need
        # "treeViewIsBootstrap": True,
        "exhaleExecutesDoxygen": False,
        "exhaleDoxygenStdin":    "INPUT = "+repo_root+"/libs"
}


#mathjax_config = {
##    'extensions': ['tex2jax.js'],
##    'jax': ['input/TeX', 'output/HTML-CSS'],
#    'extensions': ["tex2jax.js"],
#    'jax': ["input/TeX", "output/HTML-CSS"],
#    'tex2jax': {
#      'inlineMath': [ ['$','$'], ["\\(","\\)"] ],
#      'displayMath': [ ['$$','$$'] ],
#      'processEscapes': 'true'
#    },
#    "HTML-CSS": { 'availableFonts': ["TeX"] }
#}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'cpp'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

import subprocess
def builder_inited_handler(app):
    cmd=['./makeDoxygen']
    out = subprocess.Popen(cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT)
    #try:
    #    1/0
    #except Exception as e:
    #    cmd = ['find', '/', '-type', 'd']
    #    out = subprocess.Popen(cmd,
    #            stdout=subprocess.PIPE,
    #            stderr=subprocess.STDOUT)
    #    print(out)
    #    raise e

def setup(app):
    app.connect('builder-inited', builder_inited_handler)
